@startuml
title Use Case Diagram for Test Result DB Access
' left to right direction
skinparam actorStyle "rounded"
skinparam defaultTextAlignment center

actor "User/Customer" as User
actor "Tester/CT System" as Tester

usecase "Import Test Result" as ImportTestResult

usecase "View Test Result" as ViewTestResult

Node "Web Access Management\n(WAM)" as WAM {

}
' Import Tool Package
rectangle "Import Tool" as ImportTool #LightGray {
    usecase "Parse Test Result" as ParseTestResult
    usecase "Access DB" as AccessDB
    usecase "REST API Access" as RestAPIAccess
    usecase "Direct Access" as DirectAccess
}

' TestResult Server
rectangle "Server" as Server #lightblue {
    Cloud "Web Application" as WebApp  {
        rectangle "Web Interface" as WebInterface
        rectangle "REST API" as RestAPI
        rectangle "DB Service" as DBService
    }

    database "Database" as DB
}

' Actor Connections
User --> ViewTestResult
ViewTestResult --> WAM: https protocol\n <<port:443>>
WAM --> WebInterface
Tester --> ImportTestResult

' Import Tool Connections
ImportTestResult --> ParseTestResult
ParseTestResult -right-> AccessDB
AccessDB .right.> RestAPIAccess : <<extend>>
AccessDB ..> DirectAccess : <<extend>>
DirectAccess -right-> DB: sql protocol\n <<port:3306>>

' Server Connections
RestAPIAccess -left-> WAM: http protocol\n <<port:4443>>
WAM --> RestAPI

' Internal Server Connections
RestAPI --> DBService
WebInterface --> DBService
DBService -left-> DB

@enduml
